sudo: false
language: ruby

cache: bundler

script:
  - bundle exec rake lint
  - bundle exec rake validate
  - bundle exec rake spec

matrix:
  fast_finish: true

  include:
    # Unit tests
    - rvm: 1.9.3
      env: PUPPET_VERSION='~> 3.7.0'
    - rvm: 1.9.3
      env: PUPPET_VERSION='~> 3.8.0'
    - rvm: 1.9.3
      env: PUPPET_VERSION='~> 4.0.0'
    - rvm: 1.9.3
      env: PUPPET_VERSION='~> 4.1.0'
    - rvm: 1.9.3
      env: PUPPET_VERSION='~> 4.2.0'
    - rvm: 2.3.0
      env: PUPPET_VERSION='~> 4.0.0'
    - rvm: 2.3.0
      env: PUPPET_VERSION='~> 4.1.0'
    - rvm: 2.3.0
      env: PUPPET_VERSION='~> 4.2.0'

    # Acceptance tests
    - rvm: default
      sudo: required
      services: docker
      env: BEAKER_set=centos-6-x64
      script: bundle exec rake beaker

notifications:
  email: false
